/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Card */
        get: operations["fetch_card_cards__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Search */
        get: operations["stream_search_search_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/json-dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Json Dataset */
        post: operations["ingest_json_dataset_ingest_json_dataset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Embeddings */
        post: operations["create_embeddings_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/search_index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Search Index Endpoint */
        post: operations["create_search_index_endpoint_embeddings_search_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_embeddings_embeddings_post */
        Body_create_embeddings_embeddings_post: {
            /** Source Collection */
            source_collection: string;
            /** Target Collection */
            target_collection: string;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
        };
        /** Body_create_search_index_endpoint_embeddings_search_index_post */
        Body_create_search_index_endpoint_embeddings_search_index_post: {
            /** Collection Name */
            collection_name: string;
            /** Collection Field */
            collection_field: string;
            /**
             * Similarity
             * @default dot_product
             * @enum {string}
             */
            similarity: "dot_product" | "cosine" | "euclidean";
        };
        /** Body_ingest_json_dataset_ingest_json_dataset_post */
        Body_ingest_json_dataset_ingest_json_dataset_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Collection */
            collection: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckResponse */
        HealthCheckResponse: {
            /** Hello */
            Hello: string;
        };
        /** OperationMessageResponse */
        OperationMessageResponse: {
            /** Message */
            message: string;
        };
        /** ScryfallCardFace */
        ScryfallCardFace: {
            /** Name */
            name: string;
            /** Mana Cost */
            mana_cost: string;
            /** Type Line */
            type_line?: string | null;
            /** Oracle Text */
            oracle_text?: string | null;
            /** Colors */
            colors?: (("W" | "R" | "B" | "U" | "G") | null)[] | ("W" | "R" | "B" | "U" | "G") | null;
            image_uris?: components["schemas"]["ScryfallImageUris"] | null;
        };
        /** ScryfallCardPrices */
        ScryfallCardPrices: {
            /** Usd */
            usd?: string | null;
            /** Usd Foil */
            usd_foil?: string | null;
            /** Usd Etched */
            usd_etched?: string | null;
            /** Eur */
            eur?: string | null;
            /** Eur Foil */
            eur_foil?: string | null;
            /** Tix */
            tix?: string | null;
        };
        /** ScryfallCardPurchaseUris */
        ScryfallCardPurchaseUris: {
            /** Tcgplayer */
            tcgplayer?: string | null;
            /** Cardmarket */
            cardmarket?: string | null;
            /** Cardhoarder */
            cardhoarder?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ScryfallCardRecord */
        ScryfallCardRecord: {
            /**
             * Object
             * @constant
             */
            object: "card";
            /** Oracle Id */
            oracle_id: string;
            /** Multiverse Ids */
            multiverse_ids: number[];
            /** Resource Id */
            resource_id?: string | null;
            /** Mtgo Id */
            mtgo_id?: number | null;
            /** Mtgo Foil Id */
            mtgo_foil_id?: number | null;
            /** Arena Id */
            arena_id?: number | null;
            /** Tcgplayer Id */
            tcgplayer_id?: number | null;
            /** Cardmarket Id */
            cardmarket_id?: number | null;
            /** Name */
            name: string;
            /** Lang */
            lang: string;
            /** Released At */
            released_at: string;
            /** Uri */
            uri: string;
            /** Scryfall Uri */
            scryfall_uri: string;
            /** Layout */
            layout: string;
            /** Highres Image */
            highres_image: boolean;
            /** Image Status */
            image_status: string;
            image_uris?: components["schemas"]["ScryfallImageUris"] | null;
            /** Card Faces */
            card_faces?: components["schemas"]["ScryfallCardFace"][] | null;
            /** Mana Cost */
            mana_cost?: string | null;
            /** Cmc */
            cmc: number;
            /** Type Line */
            type_line: string;
            /** Oracle Text */
            oracle_text?: string | null;
            /** Power */
            power?: string | null;
            /** Toughness */
            toughness?: string | null;
            /**
             * Colors
             * @default []
             */
            colors: (("W" | "R" | "B" | "U" | "G") | null)[];
            /** Color Identity */
            color_identity: (("W" | "R" | "B" | "U" | "G") | null)[];
            /** Keywords */
            keywords: string[];
            /** Produced Mana */
            produced_mana?: string[] | null;
            /** Legalities */
            legalities: {
                [key: string]: "legal" | "not_legal" | "restricted" | "banned";
            };
            /** Games */
            games: string[];
            /** Reserved */
            reserved: boolean;
            /** Game Changer */
            game_changer: boolean;
            /** Foil */
            foil: boolean;
            /** Nonfoil */
            nonfoil: boolean;
            /** Finishes */
            finishes: string[];
            /** Oversized */
            oversized: boolean;
            /** Promo */
            promo: boolean;
            /** Reprint */
            reprint: boolean;
            /** Variation */
            variation: boolean;
            /** Set Id */
            set_id: string;
            /** Set */
            set: string;
            /** Set Name */
            set_name: string;
            /** Set Type */
            set_type: string;
            /** Set Uri */
            set_uri: string;
            /** Set Search Uri */
            set_search_uri: string;
            /** Scryfall Set Uri */
            scryfall_set_uri: string;
            /** Rulings Uri */
            rulings_uri: string;
            /** Prints Search Uri */
            prints_search_uri: string;
            /** Collector Number */
            collector_number: string;
            /** Digital */
            digital: boolean;
            /** Rarity */
            rarity: string;
            /** Flavor Text */
            flavor_text?: string | null;
            /** Card Back Id */
            card_back_id?: string | null;
            /** Artist */
            artist: string;
            /** Artist Ids */
            artist_ids?: string[] | null;
            /** Illustration Id */
            illustration_id?: string | null;
            /** Border Color */
            border_color: string;
            /** Frame */
            frame: string;
            /** Frame Effects */
            frame_effects?: string[] | null;
            /** Full Art */
            full_art: boolean;
            /** Textless */
            textless: boolean;
            /** Booster */
            booster: boolean;
            /** Story Spotlight */
            story_spotlight: boolean;
            /** Edhrec Rank */
            edhrec_rank?: number | null;
            /** Penny Rank */
            penny_rank?: number | null;
            prices: components["schemas"]["ScryfallCardPrices"];
            related_uris?: components["schemas"]["ScryfallCardRelatedUris"] | null;
            purchase_uris?: components["schemas"]["ScryfallCardPurchaseUris"] | null;
            /** Id */
            _id: string;
        };
        /** ScryfallCardRelatedUris */
        ScryfallCardRelatedUris: {
            /** Gatherer */
            gatherer?: string | null;
            /** Tcgplayer Infinite Articles */
            tcgplayer_infinite_articles?: string | null;
            /** Tcgplayer Infinite Decks */
            tcgplayer_infinite_decks?: string | null;
            /** Edhrec */
            edhrec?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ScryfallImageUris */
        ScryfallImageUris: {
            /** Small */
            small: string;
            /** Normal */
            normal: string;
            /** Large */
            large: string;
            /** Png */
            png: string;
            /** Art Crop */
            art_crop: string;
            /** Border Crop */
            border_crop: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Answer */
            answer: string;
            /** Source Id */
            source_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    fetch_card_cards__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScryfallCardRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search__get: {
        parameters: {
            query: {
                question: string;
                normalize_embeddings?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_search_search_stream_get: {
        parameters: {
            query: {
                question: string;
                normalize_embeddings?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_json_dataset_ingest_json_dataset_post: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_json_dataset_ingest_json_dataset_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_embeddings_embeddings_post: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_embeddings_embeddings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_search_index_endpoint_embeddings_search_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_search_index_endpoint_embeddings_search_index_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
